version: 2

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $SERVER_USER@$SERVER_IP "./deploy-backend-nbashop-main.sh"

# Orchestrate our job run sequence

workflows:
  version: 2
  build-project:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - ver-2.0.0


